// <auto-generated />
using CitiesManagement.WebApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitiesManagement.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CitiesManagement.WebApi.CityModel", b =>
                {
                    b.Property<string>("CityId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CityName")
                        .HasColumnType("longtext");

                    b.HasKey("CityId");

                    b.ToTable("City");
                });
#pragma warning restore 612, 618
        }
    }
}
